# Generated by Django 5.2.6 on 2025-10-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0002_externaljob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externaljob',
            options={'ordering': ['-created_at'], 'verbose_name': 'External Job', 'verbose_name_plural': 'External Jobs'},
        ),
        migrations.AlterField(
            model_name='externaljob',
            name='category',
            field=models.CharField(default='Technology', max_length=100),
        ),
    ]
