# Generated by Django 5.2.6 on 2025-10-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0003_alter_externaljob_options_alter_externaljob_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalJob',
        ),
    ]
